// @ts-nocheck
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/accounts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * Get accounts
         * @description Get all accounts
         */
    get: operations['getAccounts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
         * Update account
         * @description Update one account
         */
    patch: operations['updateAccount']
    trace?: never
  }
  [path: `/accounts/${string}`]: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * Get account
         * @description Get one account
         */
    get: operations['getAccount']
    put?: never
    post?: never
    /**
         * Delete account
         * @description Delete one account
         */
    delete: operations['deleteAccount']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  [path: `/accounts/${string}/followers`]: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * Get account followers
         * @description Get all account followers
         */
    get: operations['getAccountFollowers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  [path: `/accounts/${string}/followings`]: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * Get account followings
         * @description Get all account followings
         */
    get: operations['getAccountFollowings']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  [path: `/accounts/${string}/follow`]: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
         * Follow account
         * @description Follow account
         */
    post: operations['followAccount']
    /**
         * Unfollow account
         * @description Unfollow account
         */
    delete: operations['unfollowAccount']
    options?: never
    head?: never
    /**
         * Update follow
         * @description Update follow relationship
         */
    patch: operations['updateFollow']
    trace?: never
  }
  '/follow-requests': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * Get follow requests
         * @description Get all follow requests
         */
    get: operations['getFollowRequests']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  [path: `/follow-requests/${string}`]: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * Get follow request
         * @description Get one follow request
         */
    get: operations['getFollowRequest']
    put?: never
    post?: never
    /**
         * Delete follow request
         * @description Delete one follow request
         */
    delete: operations['deleteFollowRequest']
    options?: never
    head?: never
    /**
         * Update follow request
         * @description Update one follow request
         */
    patch: operations['updateFollowRequest']
    trace?: never
  }
  '/notifications': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * Get notifications
         * @description Get all notifications
         */
    get: operations['getNotifications']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  [path: `/notifications/${string}`]: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
         * Update notification
         * @description Update one notification
         */
    patch: operations['updateNotification']
    trace?: never
  }
  '/activities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * Get activities
         * @description Get all activities
         */
    get: operations['getActivities']
    put?: never
    /**
         * Create activity
         * @description Create activity
         */
    post: operations['createActivity']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  [path: `/activities/${string}`]: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * Get activity
         * @description Get one activity
         */
    get: operations['getActivity']
    put?: never
    post?: never
    /**
         * Delete activity
         * @description Delete one activity
         */
    delete: operations['deleteActivity']
    options?: never
    head?: never
    /**
         * Update activity
         * @description Update one activity
         */
    patch: operations['updateActivity']
    trace?: never
  }
  [path: `/activities/${string}/participants`]: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * Get activity participants
         * @description Get all activity participants
         */
    get: operations['getActivityParticipants']
    put?: never
    /**
         * Join activity
         * @description Join activity
         */
    post: operations['joinActivity']
    /**
         * Leave activity
         * @description Leave activity
         */
    delete: operations['leaveActivity']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/activities/categories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * Get activity categories
         * @description Get all activity categories
         */
    get: operations['getActivityCategories']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/establishments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * Get establishments
         * @description Get all establishments
         */
    get: operations['getEstablishments']
    put?: never
    /**
         * Create establishment
         * @description Create establishment
         */
    post: operations['createEstablishment']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  [path: `/establishments/${string}`]: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * Get establishment
         * @description Get one establishment
         */
    get: operations['getEstablishment']
    put?: never
    post?: never
    /**
         * Delete establishment
         * @description Delete one establishment
         */
    delete: operations['deleteEstablishment']
    options?: never
    head?: never
    /**
         * Update establishment
         * @description Update one establishment
         */
    patch: operations['updateEstablishment']
    trace?: never
  }
  '/establishments/requests': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
         * Get establishments requests
         * @description Get all establishment requests
         */
    get: operations['getEstablishmentRequests']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  [path: `/establishments/requests/${string}`]: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
         * Delete establishment request
         * @description Delete one establishment request
         */
    delete: operations['deleteEstablishmentRequest']
    options?: never
    head?: never
    /**
         * Update establishment request
         * @description Update one establishment request
         */
    patch: operations['updateEstablishmentRequest']
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AccountDTO: components['schemas']['AccountPersonalDTO'] | components['schemas']['AccountEnterpriseDTO']
    AccountPersonalDTO: {
      /**
             * @default other
             * @enum {string}
             */
      gender: 'male' | 'female' | 'other'
      /** Format: date */
      birthdate?: string
      /**
             * @default personal
             * @enum {string}
             */
      type: 'personal'
    } & (components['schemas']['AccountBase'] & {
      /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
      accountType: 'AccountPersonalDTO'
    })
    AccountEnterpriseDTO: {
      /** @default false */
      isVerified: boolean
      /**
             * @default enterprise
             * @enum {string}
             */
      type: 'enterprise'
    } & (components['schemas']['AccountBase'] & {
      /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
      accountType: 'AccountEnterpriseDTO'
    })
    AccountBase: {
      /** Format: uuid */
      id: string
      name: string
      username: string
      email: string
      biography?: string
      avatar?: string
      website?: string
      /** @default false */
      isPrivate: boolean
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string
    }
    FollowDTO: {
      /** Format: uuid */
      id: string
      follower: string | components['schemas']['AccountPersonalDTO']
      following: string | components['schemas']['AccountDTO']
      /** @default true */
      isMuted: boolean
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string
    }
    FollowRequestDTO: {
      /** Format: uuid */
      id: string
      requestFrom: string | components['schemas']['AccountPersonalDTO']
      requestTo: string | components['schemas']['AccountDTO']
      /**
             * @default pending
             * @enum {string}
             */
      status: 'pending' | 'approved' | 'rejected'
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string
    }
    NotificationDTO: {
      /** Format: uuid */
      id: string
      /** @enum {string} */
      type: 'follow' | 'followRequest' | 'establishmentRequest' | 'entry' | 'activity' | 'system'
      content: string
      /** @default false */
      isRead: boolean
      owner: string | components['schemas']['AccountDTO']
      relatedAccount?: string | components['schemas']['AccountDTO']
      relatedActivity?: string | components['schemas']['ActivityDTO']
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt?: string
    }
    AddressDTO: {
      /** Format: uuid */
      id?: string
      country: string
      postalCode: string
      city: string
      street: string
      number: string
      block?: string
      floor?: string
      stair?: string
      door?: string
      coordinates: {
        /** Format: double */
        latitude: number
        /** Format: double */
        longitude: number
      }
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string
    }
    ActivityDTO: components['schemas']['ActivityOnsiteDTO'] | components['schemas']['ActivityOnlineDTO']
    ActivityOnsiteDTO: {
      location: string | components['schemas']['EstablishmentDTO'] | {
        coordinates?: {
          /** Format: double */
          latitude?: number
          /** Format: double */
          longitude?: number
        }
      }
      /**
             * @default onsite
             * @enum {string}
             */
      type: 'onsite'
    } & (components['schemas']['ActivityBase'] & {
      /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
      activityType: 'ActivityOnsiteDTO'
    })
    ActivityOnlineDTO: {
      location: {
        url: string
      }
      /**
             * @default online
             * @enum {string}
             */
      type: 'online'
    } & (components['schemas']['ActivityBase'] & {
      /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
      activityType: 'ActivityOnlineDTO'
    })
    ActivityBase: {
      /** Format: uuid */
      id?: string
      owner: string | components['schemas']['AccountDTO']
      category: string | components['schemas']['ActivityCategoryDTO']
      title: string
      description: string
      /** @default [] */
      images: string[]
      time: {
        /** Format: date-time */
        start?: string
        /** Format: date-time */
        end?: string
      }
      price?: {
        /**
                 * Format: double
                 * @default 0
                 */
        min: number
        /**
                 * Format: double
                 * @default 0
                 */
        max: number
        currency?: string
      }
      participants?: {
        /** Format: int32 */
        min?: number
        /** Format: int32 */
        max?: number
      }
      /** @enum {string} */
      language: 'en' | 'es'
      website?: string
      /** @default true */
      isDraft: boolean
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string
    }
    ActivityCategoryDTO: {
      /** Format: uuid */
      id: string
      parent?: string | components['schemas']['ActivityCategoryDTO']
      name: string
      i18nKey: string
      icon: string
      color?: string
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string
    }
    ActivityParticipantDTO: {
      /** Format: uuid */
      id: string
      activity: string | components['schemas']['ActivityDTO']
      account: string | components['schemas']['AccountPersonalDTO']
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string
    }
    EstablishmentDTO: {
      /** Format: uuid */
      id?: string
      owner: string | components['schemas']['AccountEnterpriseDTO']
      address: string | components['schemas']['AddressDTO']
      name: string
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string
    }
    EstablishmentRequestDTO: {
      /** Format: uuid */
      id?: string
      requestFromActivity: string | components['schemas']['ActivityOnsiteDTO']
      requestToEstablishment: string | components['schemas']['EstablishmentDTO']
      /**
             * @default pending
             * @enum {string}
             */
      status: 'pending' | 'approved' | 'rejected'
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string
    }
    PaginatedDTO: {
      _meta?: {
        /** @example 1 */
        page?: number
        /** @example 10 */
        limit?: number
        /** @example 0 */
        results?: number
        /** @example 0 */
        total?: number
      }
    }
    AccountsPaginatedDTO: {
      data: Array<components['schemas']['AccountDTO']>
    } & components['schemas']['PaginatedDTO']
    AccountsPersonalPaginatedDTO: {
      data: Array<components['schemas']['AccountPersonalDTO']>
    } & components['schemas']['PaginatedDTO']
    FollowRequestsPaginatedDTO: {
      data: Array<components['schemas']['FollowRequestDTO']>
    } & components['schemas']['PaginatedDTO']
    NotificationsPaginatedDTO: {
      data: Array<components['schemas']['NotificationDTO']>
    } & components['schemas']['PaginatedDTO']
    ActivitiesPaginatedDTO: {
      data: Array<components['schemas']['ActivityDTO']>
    } & components['schemas']['PaginatedDTO']
    EstablishmentsPaginatedDTO: {
      data: Array<components['schemas']['EstablishmentDTO']>
    } & components['schemas']['PaginatedDTO']
    EstablishmentRequestsPaginatedDTO: {
      data: Array<components['schemas']['EstablishmentRequestDTO']>
    } & components['schemas']['PaginatedDTO']
    AccountsResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
    } & components['schemas']['AccountsPaginatedDTO']
    AccountsPersonalResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
    } & components['schemas']['AccountsPersonalPaginatedDTO']
    AccountResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
      data: components['schemas']['AccountDTO']
    }
    FollowResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
      data: components['schemas']['FollowDTO']
    }
    FollowRequestsResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
    } & components['schemas']['FollowRequestsPaginatedDTO']
    FollowRequestResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
      data: components['schemas']['FollowRequestDTO']
    }
    NotificationsResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
    } & components['schemas']['NotificationsPaginatedDTO']
    NotificationResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
      data: components['schemas']['NotificationDTO']
    }
    ActivitiesResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
    } & components['schemas']['ActivitiesPaginatedDTO']
    ActivityResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
      data: components['schemas']['ActivityDTO']
    }
    ActivityParticipantsResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
    } & components['schemas']['AccountsPersonalPaginatedDTO']
    ActivityParticipantResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
      data: components['schemas']['ActivityParticipantDTO']
    }
    ActivityCategoriesResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
      data: Array<components['schemas']['ActivityCategoryDTO']>
    }
    EstablishmentsResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
    } & components['schemas']['EstablishmentsPaginatedDTO']
    EstablishmentResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
      data: components['schemas']['EstablishmentDTO']
    }
    EstablishmentRequestsResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
    } & components['schemas']['EstablishmentRequestsPaginatedDTO']
    EstablishmentRequestResponse: {
      /**
             * @default success
             * @enum {string}
             */
      status: 'success'
      data: components['schemas']['EstablishmentRequestDTO']
    }
  }
  responses: {
    /** @description Bad Request */
    BadRequestError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /**
                     * @default error
                     * @enum {string}
                     */
          status: 'error'
          /**
                     * Format: int32
                     * @example 400
                     */
          statusCode?: number
          errors?: Array<{
            /** @example INVALID_EMAIL_FORMAT */
            code?: string
            /** @example Email format not valid */
            message?: string
            /** @example Use user@domain.com format */
            details?: string
          }>
        }
      }
    }
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /**
                     * @default error
                     * @enum {string}
                     */
          status: 'error'
          /**
                     * Format: int32
                     * @example 401
                     */
          statusCode?: number
          error?: {
            /** @example UNAUTHORIZED */
            code?: string
            /** @example Unauthorized */
            message?: string
            /** @example You must be logged in to access this resource */
            details?: string
          }
        }
      }
    }
    /** @description Forbidden */
    ForbiddenError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /**
                     * @default error
                     * @enum {string}
                     */
          status: 'error'
          /**
                     * Format: int32
                     * @example 403
                     */
          statusCode?: number
          error?: {
            /** @example FORBIDDEN */
            code?: string
            /** @example Forbidden */
            message?: string
            /** @example You do not have permission to access this resource */
            details?: string
          }
        }
      }
    }
    /** @description Not Found */
    NotFoundError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /**
                     * @default error
                     * @enum {string}
                     */
          status: 'error'
          /**
                     * Format: int32
                     * @example 404
                     */
          statusCode?: number
          error?: {
            /** @example NOT_FOUND */
            code?: string
            /** @example Resource not found */
            message?: string
            /** @example The requested resource could not be found */
            details?: string
          }
        }
      }
    }
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /**
                     * @default error
                     * @enum {string}
                     */
          status: 'error'
          /**
                     * Format: int32
                     * @example 500
                     */
          statusCode?: number
          error?: {
            /** @example INTERNAL_SERVER_ERROR */
            code?: string
            /** @example An unexpected error occurred */
            message?: string
            /** @example Please try again later or contact support */
            details?: string
          }
        }
      }
    }
  }
  parameters: {
    /** @description Page number for pagination */
    pageQueryParam: number
    /** @description Number of items per page for pagination */
    limitQueryParam: number
    /** @description Account ID */
    accountIdPathParam: string
    /** @description Account ID */
    accountIdQueryParam: string
    /** @description Account type */
    accountTypeQueryParam: 'personal' | 'enterprise'
    /** @description Account name */
    accountNameQueryParam: string
    /** @description Account username */
    accountUsernameQueryParam: string
    /** @description Follow request ID */
    followRequestIdPathParam: string
    /** @description Notification ID */
    notificationIdPathParam: string
    /** @description Establishment ID */
    establishmentIdPathParam: string
    /** @description Activity ID */
    activityIdQueryParam: string
    /** @description Establishment ID */
    establishmentIdQueryParam: string
    /** @description Establishment name */
    establishmentNameQueryParam: string
    /** @description Establishment address */
    establishmentAddressQueryParam: string
    /** @description Establishment owner ID */
    establishmentOwnerQueryParam: string
    /** @description Establishment request ID */
    establishmentRequestIdPathParam: string
    /** @description Activity ID */
    activityIdPathParam: string
    /** @description Activity title */
    activityTitleQueryParam: string
    /** @description Activity description */
    activityDescriptionQueryParam: string
    /** @description Activity category ID */
    activityCategoryIdQueryParam: string
    /** @description Activity min price */
    activityMinPriceQueryParam: number
    /** @description Activity max price */
    activityMaxPriceQueryParam: number
    /** @description Activity language */
    activityLanguageQueryParam: string
    /** @description Activity type */
    activityTypeQueryParam: 'onsite' | 'online'
    /** @description Activity time start */
    activityTimeStartQueryParam: string
    /** @description Activity time end */
    activityTimeEndQueryParam: string
    /** @description Activity min participants */
    activityMinParcipantsQueryParam: number
    /** @description Activity max participants */
    activityMaxParcipantsQueryParam: number
    /** @description Activity min entries */
    activityMinEntriesQueryParam: number
    /** @description Activity max entries */
    activityMaxEntriesQueryParam: number
    /** @description Activity geolocation */
    activityGeolocationQueryParam: {
      /** Format: double */
      latitude?: number
      /** Format: double */
      longitude?: number
      /**
             * Format: double
             * @default 1000
             */
      radius?: number
    }
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getAccounts: {
    parameters: {
      query?: {
        /** @description Page number for pagination */
        page?: components['parameters']['pageQueryParam']
        /** @description Number of items per page for pagination */
        limit?: components['parameters']['limitQueryParam']
        /** @description Account type */
        type?: components['parameters']['accountTypeQueryParam']
        /** @description Account name */
        name?: components['parameters']['accountNameQueryParam']
        /** @description Account username */
        username?: components['parameters']['accountUsernameQueryParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountsResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      500: components['responses']['InternalServerError']
    }
  }
  updateAccount: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountDTO']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  getAccount: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Account ID */
        id: components['parameters']['accountIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  deleteAccount: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Account ID */
        id: components['parameters']['accountIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  getAccountFollowers: {
    parameters: {
      query?: {
        /** @description Page number for pagination */
        page?: components['parameters']['pageQueryParam']
        /** @description Number of items per page for pagination */
        limit?: components['parameters']['limitQueryParam']
        /** @description Account name */
        name?: components['parameters']['accountNameQueryParam']
        /** @description Account username */
        username?: components['parameters']['accountUsernameQueryParam']
      }
      header?: never
      path: {
        /** @description Account ID */
        id: components['parameters']['accountIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountsPersonalResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  getAccountFollowings: {
    parameters: {
      query?: {
        /** @description Page number for pagination */
        page?: components['parameters']['pageQueryParam']
        /** @description Number of items per page for pagination */
        limit?: components['parameters']['limitQueryParam']
        /** @description Account name */
        name?: components['parameters']['accountNameQueryParam']
        /** @description Account username */
        username?: components['parameters']['accountUsernameQueryParam']
      }
      header?: never
      path: {
        /** @description Account ID */
        id: components['parameters']['accountIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountsResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  followAccount: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Account ID */
        id: components['parameters']['accountIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FollowResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  unfollowAccount: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Account ID */
        id: components['parameters']['accountIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  updateFollow: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Account ID */
        id: components['parameters']['accountIdPathParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FollowDTO']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FollowResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  getFollowRequests: {
    parameters: {
      query?: {
        /** @description Page number for pagination */
        page?: components['parameters']['pageQueryParam']
        /** @description Number of items per page for pagination */
        limit?: components['parameters']['limitQueryParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FollowRequestsResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      500: components['responses']['InternalServerError']
    }
  }
  getFollowRequest: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Follow request ID */
        id: components['parameters']['followRequestIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FollowRequestResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  deleteFollowRequest: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Follow request ID */
        id: components['parameters']['followRequestIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  updateFollowRequest: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Follow request ID */
        id: components['parameters']['followRequestIdPathParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FollowRequestDTO']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FollowRequestResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  getNotifications: {
    parameters: {
      query?: {
        /** @description Page number for pagination */
        page?: components['parameters']['pageQueryParam']
        /** @description Number of items per page for pagination */
        limit?: components['parameters']['limitQueryParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotificationsResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      500: components['responses']['InternalServerError']
    }
  }
  updateNotification: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Notification ID */
        id: components['parameters']['notificationIdPathParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NotificationDTO']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotificationResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  getActivities: {
    parameters: {
      query?: {
        /** @description Page number for pagination */
        page?: components['parameters']['pageQueryParam']
        /** @description Number of items per page for pagination */
        limit?: components['parameters']['limitQueryParam']
        /** @description Account ID */
        accountId?: components['parameters']['accountIdQueryParam']
        /** @description Activity type */
        type?: components['parameters']['activityTypeQueryParam']
        /** @description Activity title */
        title?: components['parameters']['activityTitleQueryParam']
        /** @description Activity description */
        description?: components['parameters']['activityDescriptionQueryParam']
        /** @description Activity category ID */
        categoryId?: components['parameters']['activityCategoryIdQueryParam']
        /** @description Activity min price */
        minPrice?: components['parameters']['activityMinPriceQueryParam']
        /** @description Activity max price */
        maxPrice?: components['parameters']['activityMaxPriceQueryParam']
        /** @description Activity time start */
        timeStart?: components['parameters']['activityTimeStartQueryParam']
        /** @description Activity time end */
        timeEnd?: components['parameters']['activityTimeEndQueryParam']
        /** @description Activity min participants */
        minParticipants?: components['parameters']['activityMinParcipantsQueryParam']
        /** @description Activity max participants */
        maxParticipants?: components['parameters']['activityMaxParcipantsQueryParam']
        /** @description Activity min entries */
        minEntries?: components['parameters']['activityMinEntriesQueryParam']
        /** @description Activity max entries */
        maxEntries?: components['parameters']['activityMaxEntriesQueryParam']
        /** @description Activity geolocation */
        geolocation?: components['parameters']['activityGeolocationQueryParam']
        /** @description Activity language */
        language?: components['parameters']['activityLanguageQueryParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivitiesResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      500: components['responses']['InternalServerError']
    }
  }
  createActivity: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivityDTO']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivityResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      500: components['responses']['InternalServerError']
    }
  }
  getActivity: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Activity ID */
        id: components['parameters']['activityIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivityResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  deleteActivity: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Activity ID */
        id: components['parameters']['activityIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  updateActivity: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Activity ID */
        id: components['parameters']['activityIdPathParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivityDTO']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivityResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  getActivityParticipants: {
    parameters: {
      query?: {
        /** @description Page number for pagination */
        page?: components['parameters']['pageQueryParam']
        /** @description Number of items per page for pagination */
        limit?: components['parameters']['limitQueryParam']
        /** @description Account name */
        name?: components['parameters']['accountNameQueryParam']
        /** @description Account username */
        username?: components['parameters']['accountUsernameQueryParam']
      }
      header?: never
      path: {
        /** @description Activity ID */
        id: components['parameters']['activityIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivityParticipantsResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  joinActivity: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Activity ID */
        id: components['parameters']['activityIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivityParticipantResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  leaveActivity: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Activity ID */
        id: components['parameters']['activityIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  getActivityCategories: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivityCategoriesResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      500: components['responses']['InternalServerError']
    }
  }
  getEstablishments: {
    parameters: {
      query?: {
        /** @description Page number for pagination */
        page?: components['parameters']['pageQueryParam']
        /** @description Number of items per page for pagination */
        limit?: components['parameters']['limitQueryParam']
        /** @description Establishment name */
        name?: components['parameters']['establishmentNameQueryParam']
        /** @description Establishment address */
        address?: components['parameters']['establishmentAddressQueryParam']
        /** @description Establishment owner ID */
        owner?: components['parameters']['establishmentOwnerQueryParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EstablishmentsResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      500: components['responses']['InternalServerError']
    }
  }
  createEstablishment: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EstablishmentDTO']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EstablishmentResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      500: components['responses']['InternalServerError']
    }
  }
  getEstablishment: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Establishment ID */
        id: components['parameters']['establishmentIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EstablishmentResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  deleteEstablishment: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Establishment ID */
        id: components['parameters']['establishmentIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  updateEstablishment: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Establishment ID */
        id: components['parameters']['establishmentIdPathParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EstablishmentDTO']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EstablishmentResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  getEstablishmentRequests: {
    parameters: {
      query?: {
        /** @description Page number for pagination */
        page?: components['parameters']['pageQueryParam']
        /** @description Number of items per page for pagination */
        limit?: components['parameters']['limitQueryParam']
        /** @description Activity ID */
        activityId?: components['parameters']['activityIdQueryParam']
        /** @description Establishment ID */
        establishmentId?: components['parameters']['establishmentIdQueryParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EstablishmentRequestsResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      500: components['responses']['InternalServerError']
    }
  }
  deleteEstablishmentRequest: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Establishment request ID */
        id: components['parameters']['establishmentRequestIdPathParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
  updateEstablishmentRequest: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Establishment request ID */
        id: components['parameters']['establishmentRequestIdPathParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EstablishmentRequestDTO']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EstablishmentRequestResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      500: components['responses']['InternalServerError']
    }
  }
}
